export type ImageKind =
	| "laptop"
	| "phone"
	| "tablet"
	| "monitor"
	| "headphones"
	| "earbuds"
	| "speaker"
	| "watch"
	| "controller"
	| "keyboard"
	| "mouse"
	| "charger"
	| "ssd";

export type CategorySlug =
	| "laptops"
	| "smartphones"
	| "tablets"
	| "audio"
	| "wearables"
	| "monitors"
	| "accessories"
	| "gaming";

/** One purchasable configuration; `add` is the surcharge over the base price. */
export type Tier = {
	storage?: number;
	ram?: number;
	screen?: number;
	add: number;
};

export type ProductSeed = {
	name: string;
	brand: string;
	category: CategorySlug;
	kind: ImageKind;
	price: number;
	colors: string[];
	tiers?: Tier[];
	summary: string;
	highlights: string[];
};

export const seedCategories: {
	slug: CategorySlug;
	name: string;
	icon: string;
	iconColor: string;
	iconBg: string;
}[] = [
	{
		slug: "laptops",
		name: "Laptops",
		icon: "Laptop",
		iconColor: "#4F46E5",
		iconBg: "#E0E7FF",
	},
	{
		slug: "smartphones",
		name: "Smartphones",
		icon: "Smartphone",
		iconColor: "#2563EB",
		iconBg: "#DBEAFE",
	},
	{
		slug: "tablets",
		name: "Tablets",
		icon: "Tablet",
		iconColor: "#0891B2",
		iconBg: "#CFFAFE",
	},
	{
		slug: "audio",
		name: "Audio",
		icon: "Headphones",
		iconColor: "#D97706",
		iconBg: "#FEF3C7",
	},
	{
		slug: "wearables",
		name: "Wearables",
		icon: "Watch",
		iconColor: "#059669",
		iconBg: "#D1FAE5",
	},
	{
		slug: "monitors",
		name: "Monitors",
		icon: "Monitor",
		iconColor: "#7C3AED",
		iconBg: "#EDE9FE",
	},
	{
		slug: "accessories",
		name: "Accessories",
		icon: "Cable",
		iconColor: "#475569",
		iconBg: "#E2E8F0",
	},
	{
		slug: "gaming",
		name: "Gaming",
		icon: "Gamepad2",
		iconColor: "#DC2626",
		iconBg: "#FEE2E2",
	},
];

export const colorHex: Record<string, string> = {
	Black: "#111827",
	White: "#F8FAFC",
	Silver: "#C0C0C0",
	"Space Gray": "#4B5563",
	Graphite: "#374151",
	Midnight: "#1E293B",
	Starlight: "#F1E9DA",
	Blue: "#3B82F6",
	Green: "#4D7C5F",
	Pink: "#F9A8D4",
	Purple: "#A78BFA",
	Sand: "#D6C7B0",
	Titanium: "#8E8A84",
	Red: "#DC2626",
};

// Storage, RAM, and screen tiers shared by several products.
const phoneStorage = (step: number): Tier[] => [
	{ storage: 128, add: 0 },
	{ storage: 256, add: step },
	{ storage: 512, add: step * 2.2 },
];
const laptopTiers = (step: number): Tier[] => [
	{ ram: 16, storage: 512, add: 0 },
	{ ram: 16, storage: 1024, add: step },
	{ ram: 32, storage: 1024, add: step * 2.2 },
];
const tabletStorage = (step: number): Tier[] => [
	{ storage: 128, add: 0 },
	{ storage: 256, add: step },
	{ storage: 512, add: step * 2.4 },
];
const watchSizes = (small: number, large: number, step: number): Tier[] => [
	{ screen: small, add: 0 },
	{ screen: large, add: step },
];

export const seedProducts: ProductSeed[] = [
	// Laptops
	{
		name: "MacBook Air 13 (M3)",
		brand: "Apple",
		category: "laptops",
		kind: "laptop",
		price: 1199,
		colors: ["Midnight", "Silver", "Starlight"],
		tiers: [
			{ ram: 16, storage: 256, add: 0 },
			{ ram: 16, storage: 512, add: 230 },
			{ ram: 24, storage: 512, add: 460 },
		],
		summary:
			"Fanless 13.6-inch laptop with the M3 chip and up to 18 hours of battery life.",
		highlights: [
			"Apple M3 chip with 8-core CPU",
			"13.6-inch Liquid Retina display",
			"Up to 18 hours battery life",
			"MagSafe charging and two Thunderbolt ports",
		],
	},
	{
		name: "MacBook Air 15 (M3)",
		brand: "Apple",
		category: "laptops",
		kind: "laptop",
		price: 1499,
		colors: ["Midnight", "Silver"],
		tiers: [
			{ ram: 16, storage: 256, add: 0 },
			{ ram: 16, storage: 512, add: 230 },
			{ ram: 24, storage: 1024, add: 690 },
		],
		summary: "Large 15.3-inch display in a thin, silent design.",
		highlights: [
			"15.3-inch Liquid Retina display",
			"Six-speaker sound system",
			"1080p FaceTime HD camera",
			"Fanless design",
		],
	},
	{
		name: "MacBook Pro 14 (M4)",
		brand: "Apple",
		category: "laptops",
		kind: "laptop",
		price: 1899,
		colors: ["Space Gray", "Silver"],
		tiers: laptopTiers(250),
		summary: "Pro laptop with Liquid Retina XDR display and M4 performance.",
		highlights: [
			"Liquid Retina XDR, up to 1,600 nits HDR",
			"Apple M4 with 10-core CPU",
			"Three Thunderbolt 4 ports and HDMI",
			"Up to 24 hours battery life",
		],
	},
	{
		name: "MacBook Pro 16 (M4 Pro)",
		brand: "Apple",
		category: "laptops",
		kind: "laptop",
		price: 2899,
		colors: ["Space Gray", "Silver"],
		tiers: [
			{ ram: 24, storage: 512, add: 0 },
			{ ram: 48, storage: 1024, add: 700 },
		],
		summary: "The largest MacBook Pro for demanding creative work.",
		highlights: [
			"16.2-inch Liquid Retina XDR display",
			"M4 Pro with 14-core CPU",
			"Studio-quality three-mic array",
			"SDXC card slot",
		],
	},
	{
		name: "XPS 13",
		brand: "Dell",
		category: "laptops",
		kind: "laptop",
		price: 1299,
		colors: ["Graphite", "Silver"],
		tiers: laptopTiers(200),
		summary: "Compact ultrabook with an edge-to-edge InfinityEdge display.",
		highlights: [
			"13.4-inch InfinityEdge display",
			"Intel Core Ultra 7",
			"Machined aluminium chassis",
			"Wi-Fi 7",
		],
	},
	{
		name: "XPS 14",
		brand: "Dell",
		category: "laptops",
		kind: "laptop",
		price: 1699,
		colors: ["Graphite", "Silver"],
		tiers: laptopTiers(220),
		summary: "Creator laptop with OLED option and dedicated graphics.",
		highlights: [
			"14.5-inch 3.2K OLED option",
			"NVIDIA GeForce RTX 4050",
			"Haptic touchpad",
			"Up to 32 GB LPDDR5x",
		],
	},
	{
		name: "Inspiron 15",
		brand: "Dell",
		category: "laptops",
		kind: "laptop",
		price: 649,
		colors: ["Silver", "Black"],
		tiers: [
			{ ram: 8, storage: 512, add: 0 },
			{ ram: 16, storage: 512, add: 100 },
			{ ram: 16, storage: 1024, add: 180 },
		],
		summary: "Everyday 15.6-inch laptop for work, study, and streaming.",
		highlights: [
			"15.6-inch Full HD 120 Hz display",
			"Intel Core i5",
			"Numeric keypad",
			"Fast charging",
		],
	},
	{
		name: "ThinkPad X1 Carbon Gen 12",
		brand: "Lenovo",
		category: "laptops",
		kind: "laptop",
		price: 1999,
		colors: ["Black"],
		tiers: laptopTiers(240),
		summary: "Lightweight business laptop at just 1.09 kg.",
		highlights: [
			"14-inch 2.8K OLED option",
			"Intel Core Ultra 7 vPro",
			"MIL-STD-810H tested",
			"Legendary ThinkPad keyboard",
		],
	},
	{
		name: "ThinkPad T14 Gen 5",
		brand: "Lenovo",
		category: "laptops",
		kind: "laptop",
		price: 1249,
		colors: ["Black"],
		tiers: laptopTiers(180),
		summary: "Reliable workhorse with user-replaceable memory.",
		highlights: [
			"14-inch WUXGA display",
			"AMD Ryzen 7 PRO",
			"Replaceable battery and RAM",
			"Full-size RJ45 port",
		],
	},
	{
		name: "IdeaPad Slim 5",
		brand: "Lenovo",
		category: "laptops",
		kind: "laptop",
		price: 749,
		colors: ["Graphite", "Silver"],
		tiers: [
			{ ram: 16, storage: 512, add: 0 },
			{ ram: 16, storage: 1024, add: 110 },
		],
		summary: "Slim aluminium laptop with a comfortable 16:10 display.",
		highlights: [
			"14-inch 16:10 OLED",
			"AMD Ryzen 7",
			"Fingerprint reader",
			"Up to 14 hours battery life",
		],
	},
	{
		name: "Yoga Slim 7x",
		brand: "Lenovo",
		category: "laptops",
		kind: "laptop",
		price: 1299,
		colors: ["Blue", "Graphite"],
		tiers: laptopTiers(200),
		summary: "Copilot+ PC with Snapdragon X Elite and a 3K OLED screen.",
		highlights: [
			"14.5-inch 3K OLED, 90 Hz",
			"Snapdragon X Elite",
			"Up to 20 hours battery",
			"1.28 kg",
		],
	},
	{
		name: "Spectre x360 14",
		brand: "HP",
		category: "laptops",
		kind: "laptop",
		price: 1599,
		colors: ["Midnight", "Silver"],
		tiers: laptopTiers(220),
		summary: "Convertible 2-in-1 with pen support and OLED display.",
		highlights: [
			"14-inch 2.8K OLED touch display",
			"360-degree hinge",
			"HP Rechargeable MPP2.0 Pen included",
			"9 MP IR camera",
		],
	},
	{
		name: "EliteBook 840 G11",
		brand: "HP",
		category: "laptops",
		kind: "laptop",
		price: 1449,
		colors: ["Silver"],
		tiers: laptopTiers(200),
		summary: "Secure business notebook with Wolf Security.",
		highlights: [
			"14-inch WUXGA anti-glare",
			"Intel Core Ultra 5",
			"HP Wolf Security",
			"5 MP camera with privacy shutter",
		],
	},
	{
		name: "Pavilion 15",
		brand: "HP",
		category: "laptops",
		kind: "laptop",
		price: 699,
		colors: ["Silver", "Blue"],
		tiers: [
			{ ram: 8, storage: 512, add: 0 },
			{ ram: 16, storage: 512, add: 90 },
		],
		summary: "Affordable all-rounder with a full-size keyboard.",
		highlights: [
			"15.6-inch Full HD IPS",
			"Intel Core i5",
			"Dual speakers by B&O",
			"USB-C with Power Delivery",
		],
	},
	{
		name: "Zenbook 14 OLED",
		brand: "ASUS",
		category: "laptops",
		kind: "laptop",
		price: 1099,
		colors: ["Blue", "Silver"],
		tiers: laptopTiers(160),
		summary: "Portable OLED ultrabook with long battery life.",
		highlights: [
			"14-inch 3K OLED 120 Hz",
			"Intel Core Ultra 7",
			"75 Wh battery",
			"1.2 kg",
		],
	},
	{
		name: "ROG Zephyrus G14",
		brand: "ASUS",
		category: "laptops",
		kind: "laptop",
		price: 1999,
		colors: ["Graphite", "White"],
		tiers: laptopTiers(250),
		summary: "Compact gaming laptop with RTX graphics and OLED panel.",
		highlights: [
			"14-inch 3K OLED 120 Hz",
			"NVIDIA GeForce RTX 4070",
			"AMD Ryzen 9",
			"CNC aluminium chassis",
		],
	},
	{
		name: "Swift Go 14",
		brand: "Acer",
		category: "laptops",
		kind: "laptop",
		price: 899,
		colors: ["Silver"],
		tiers: [
			{ ram: 16, storage: 512, add: 0 },
			{ ram: 16, storage: 1024, add: 120 },
		],
		summary: "Thin travel laptop with OLED display and QHD webcam.",
		highlights: [
			"14-inch 2.8K OLED",
			"Intel Core Ultra 7",
			"1440p webcam",
			"Two Thunderbolt 4 ports",
		],
	},
	{
		name: "Aspire 5",
		brand: "Acer",
		category: "laptops",
		kind: "laptop",
		price: 549,
		colors: ["Silver"],
		tiers: [
			{ ram: 8, storage: 512, add: 0 },
			{ ram: 16, storage: 512, add: 80 },
		],
		summary: "Budget-friendly laptop for everyday tasks.",
		highlights: [
			"15.6-inch Full HD",
			"Intel Core i5",
			"Backlit keyboard",
			"Wi-Fi 6",
		],
	},
	{
		name: "Surface Laptop 7",
		brand: "Microsoft",
		category: "laptops",
		kind: "laptop",
		price: 1299,
		colors: ["Silver", "Graphite"],
		tiers: laptopTiers(220),
		summary: "Copilot+ PC with Snapdragon X and a PixelSense touch display.",
		highlights: [
			"13.8-inch PixelSense Flow, 120 Hz",
			"Snapdragon X Plus",
			"Up to 20 hours video playback",
			"Studio Camera",
		],
	},
	{
		name: "Laptop 13",
		brand: "Framework",
		category: "laptops",
		kind: "laptop",
		price: 1149,
		colors: ["Silver"],
		tiers: laptopTiers(180),
		summary: "Modular, repairable laptop with swappable ports.",
		highlights: [
			"Expansion Card system",
			"Replaceable mainboard",
			"13.5-inch 2.8K display",
			"Every part has a QR code to its guide",
		],
	},
	{
		name: "Prestige 16",
		brand: "MSI",
		category: "laptops",
		kind: "laptop",
		price: 1399,
		colors: ["Graphite"],
		tiers: laptopTiers(200),
		summary: "Creator notebook with a 16-inch display and long battery.",
		highlights: [
			"16-inch QHD+ 165 Hz",
			"Intel Core Ultra 7",
			"99.9 Wh battery",
			"MIL-STD-810H",
		],
	},
	{
		name: "Galaxy Book4 Pro",
		brand: "Samsung",
		category: "laptops",
		kind: "laptop",
		price: 1499,
		colors: ["Graphite", "Silver"],
		tiers: laptopTiers(200),
		summary: "AMOLED touch laptop that pairs with Galaxy devices.",
		highlights: [
			"14-inch Dynamic AMOLED 2X",
			"Intel Core Ultra 7",
			"Galaxy ecosystem integration",
			"1.23 kg",
		],
	},

	// Smartphones
	{
		name: "iPhone 16",
		brand: "Apple",
		category: "smartphones",
		kind: "phone",
		price: 949,
		colors: ["Black", "White", "Blue", "Green"],
		tiers: phoneStorage(130),
		summary: "A18 chip, Camera Control, and a 48 MP Fusion camera.",
		highlights: [
			"6.1-inch Super Retina XDR",
			"A18 chip",
			"Camera Control button",
			"48 MP Fusion camera",
		],
	},
	{
		name: "iPhone 16 Plus",
		brand: "Apple",
		category: "smartphones",
		kind: "phone",
		price: 1099,
		colors: ["Black", "White", "Pink"],
		tiers: phoneStorage(130),
		summary:
			"Bigger display and the longest battery life in the iPhone 16 lineup.",
		highlights: [
			"6.7-inch Super Retina XDR",
			"A18 chip",
			"Action button",
			"USB-C",
		],
	},
	{
		name: "iPhone 16 Pro",
		brand: "Apple",
		category: "smartphones",
		kind: "phone",
		price: 1199,
		colors: ["Titanium", "Black", "White"],
		tiers: phoneStorage(130),
		summary: "Titanium design with a 5x Telephoto camera.",
		highlights: [
			"6.3-inch ProMotion display",
			"A18 Pro chip",
			"5x Telephoto",
			"4K120 Dolby Vision video",
		],
	},
	{
		name: "iPhone 16 Pro Max",
		brand: "Apple",
		category: "smartphones",
		kind: "phone",
		price: 1449,
		colors: ["Titanium", "Black"],
		tiers: [
			{ storage: 256, add: 0 },
			{ storage: 512, add: 250 },
			{ storage: 1024, add: 500 },
		],
		summary: "The biggest iPhone display with pro camera system.",
		highlights: [
			"6.9-inch ProMotion display",
			"A18 Pro chip",
			"48 MP Ultra Wide",
			"Longest iPhone battery life",
		],
	},
	{
		name: "iPhone 15",
		brand: "Apple",
		category: "smartphones",
		kind: "phone",
		price: 799,
		colors: ["Black", "Blue", "Green", "Pink"],
		tiers: phoneStorage(120),
		summary: "Dynamic Island and a 48 MP main camera.",
		highlights: [
			"6.1-inch Super Retina XDR",
			"A16 Bionic",
			"Dynamic Island",
			"USB-C",
		],
	},
	{
		name: "Galaxy S24",
		brand: "Samsung",
		category: "smartphones",
		kind: "phone",
		price: 899,
		colors: ["Black", "Purple", "Sand"],
		tiers: phoneStorage(60),
		summary: "Compact flagship with Galaxy AI features.",
		highlights: [
			"6.2-inch Dynamic AMOLED 2X",
			"Galaxy AI",
			"50 MP triple camera",
			"7 years of OS updates",
		],
	},
	{
		name: "Galaxy S24+",
		brand: "Samsung",
		category: "smartphones",
		kind: "phone",
		price: 1149,
		colors: ["Black", "Purple"],
		tiers: [
			{ storage: 256, add: 0 },
			{ storage: 512, add: 120 },
		],
		summary: "Larger QHD+ display and 12 GB RAM.",
		highlights: [
			"6.7-inch QHD+ display",
			"12 GB RAM",
			"4,900 mAh battery",
			"45 W charging",
		],
	},
	{
		name: "Galaxy S24 Ultra",
		brand: "Samsung",
		category: "smartphones",
		kind: "phone",
		price: 1449,
		colors: ["Titanium", "Black"],
		tiers: [
			{ storage: 256, add: 0 },
			{ storage: 512, add: 120 },
			{ storage: 1024, add: 360 },
		],
		summary: "Titanium frame, built-in S Pen, and 200 MP camera.",
		highlights: [
			"6.8-inch QHD+ display",
			"Built-in S Pen",
			"200 MP wide camera",
			"Corning Gorilla Armor",
		],
	},
	{
		name: "Galaxy A55 5G",
		brand: "Samsung",
		category: "smartphones",
		kind: "phone",
		price: 479,
		colors: ["Blue", "Black"],
		tiers: [
			{ storage: 128, add: 0 },
			{ storage: 256, add: 70 },
		],
		summary: "Mid-range phone with a premium metal frame.",
		highlights: [
			"6.6-inch Super AMOLED 120 Hz",
			"IP67",
			"50 MP OIS camera",
			"5,000 mAh battery",
		],
	},
	{
		name: "Galaxy Z Flip6",
		brand: "Samsung",
		category: "smartphones",
		kind: "phone",
		price: 1199,
		colors: ["Blue", "Green", "Silver"],
		tiers: [
			{ storage: 256, add: 0 },
			{ storage: 512, add: 120 },
		],
		summary: "Foldable phone with a larger FlexWindow cover screen.",
		highlights: [
			"3.4-inch FlexWindow",
			"50 MP main camera",
			"IP48",
			"FlexCam hands-free shots",
		],
	},
	{
		name: "Pixel 9",
		brand: "Google",
		category: "smartphones",
		kind: "phone",
		price: 899,
		colors: ["Black", "Pink", "Green"],
		tiers: [
			{ storage: 128, add: 0 },
			{ storage: 256, add: 100 },
		],
		summary: "Google Tensor G4 with Gemini built in.",
		highlights: [
			"6.3-inch Actua display",
			"Google Tensor G4",
			"Add Me photo feature",
			"7 years of updates",
		],
	},
	{
		name: "Pixel 9 Pro",
		brand: "Google",
		category: "smartphones",
		kind: "phone",
		price: 1099,
		colors: ["Black", "White", "Pink"],
		tiers: phoneStorage(110),
		summary: "Pro camera system with 5x optical zoom.",
		highlights: [
			"6.3-inch Super Actua display",
			"16 GB RAM",
			"48 MP 5x telephoto",
			"Video Boost",
		],
	},
	{
		name: "Pixel 8a",
		brand: "Google",
		category: "smartphones",
		kind: "phone",
		price: 549,
		colors: ["Black", "Blue", "Green"],
		tiers: [
			{ storage: 128, add: 0 },
			{ storage: 256, add: 60 },
		],
		summary: "Affordable Pixel with Tensor G3 and great photos.",
		highlights: [
			"6.1-inch Actua display 120 Hz",
			"Tensor G3",
			"Magic Eraser",
			"IP67",
		],
	},
	{
		name: "12",
		brand: "OnePlus",
		category: "smartphones",
		kind: "phone",
		price: 899,
		colors: ["Green", "Black"],
		tiers: [
			{ storage: 256, add: 0 },
			{ storage: 512, add: 100 },
		],
		summary: "Fast-charging flagship with Hasselblad camera.",
		highlights: [
			"6.82-inch 2K ProXDR",
			"80 W SUPERVOOC",
			"Hasselblad camera",
			"Snapdragon 8 Gen 3",
		],
	},
	{
		name: "Nord 4",
		brand: "OnePlus",
		category: "smartphones",
		kind: "phone",
		price: 499,
		colors: ["Silver", "Black"],
		tiers: [
			{ storage: 256, add: 0 },
			{ storage: 512, add: 70 },
		],
		summary: "Metal unibody mid-ranger with 100 W charging.",
		highlights: [
			"6.74-inch AMOLED 120 Hz",
			"100 W charging",
			"Metal unibody",
			"Snapdragon 7+ Gen 3",
		],
	},
	{
		name: "14",
		brand: "Xiaomi",
		category: "smartphones",
		kind: "phone",
		price: 999,
		colors: ["Black", "White", "Green"],
		tiers: [
			{ storage: 256, add: 0 },
			{ storage: 512, add: 100 },
		],
		summary: "Compact flagship with Leica optics.",
		highlights: [
			"6.36-inch LTPO AMOLED",
			"Leica Summilux lens",
			"90 W HyperCharge",
			"Snapdragon 8 Gen 3",
		],
	},
	{
		name: "Redmi Note 13 Pro",
		brand: "Xiaomi",
		category: "smartphones",
		kind: "phone",
		price: 349,
		colors: ["Black", "Purple"],
		tiers: [
			{ storage: 256, add: 0 },
			{ storage: 512, add: 60 },
		],
		summary: "200 MP camera at a mid-range price.",
		highlights: [
			"200 MP main camera",
			"6.67-inch AMOLED 120 Hz",
			"67 W charging",
			"IP54",
		],
	},
	{
		name: "Phone (2a)",
		brand: "Nothing",
		category: "smartphones",
		kind: "phone",
		price: 349,
		colors: ["Black", "White"],
		tiers: [
			{ storage: 128, add: 0 },
			{ storage: 256, add: 50 },
		],
		summary: "Distinctive transparent design with Glyph Interface.",
		highlights: [
			"Glyph Interface",
			"6.7-inch AMOLED",
			"Nothing OS 2.5",
			"50 MP dual camera",
		],
	},
	{
		name: "Fairphone 5",
		brand: "Fairphone",
		category: "smartphones",
		kind: "phone",
		price: 699,
		colors: ["Black", "Blue"],
		tiers: [{ storage: 256, add: 0 }],
		summary: "Modular, repairable phone with long software support.",
		highlights: [
			"User-replaceable battery",
			"Fairly sourced materials",
			"Up to 8 years of updates",
			"5-year warranty",
		],
	},
	{
		name: "Xperia 10 VI",
		brand: "Sony",
		category: "smartphones",
		kind: "phone",
		price: 399,
		colors: ["Black", "White", "Blue"],
		tiers: [{ storage: 128, add: 0 }],
		summary: "Lightweight phone with a 3.5 mm headphone jack.",
		highlights: [
			"6.1-inch OLED 21:9",
			"5,000 mAh battery",
			"3.5 mm audio jack",
			"Front stereo speakers",
		],
	},
	{
		name: "edge 50 pro",
		brand: "Motorola",
		category: "smartphones",
		kind: "phone",
		price: 549,
		colors: ["Black", "Purple"],
		tiers: [
			{ storage: 256, add: 0 },
			{ storage: 512, add: 70 },
		],
		summary: "Curved pOLED display and 125 W TurboPower charging.",
		highlights: [
			"6.7-inch 1.5K pOLED 144 Hz",
			"125 W TurboPower",
			"Pantone-validated colours",
			"IP68",
		],
	},
	{
		name: "Galaxy S23 FE",
		brand: "Samsung",
		category: "smartphones",
		kind: "phone",
		price: 549,
		colors: ["Purple", "Green", "Black"],
		tiers: [
			{ storage: 128, add: 0 },
			{ storage: 256, add: 60 },
		],
		summary: "Fan Edition with flagship camera features.",
		highlights: [
			"6.4-inch Dynamic AMOLED 2X",
			"50 MP triple camera",
			"IP68",
			"Wireless PowerShare",
		],
	},

	// Tablets
	{
		name: "iPad (10th generation)",
		brand: "Apple",
		category: "tablets",
		kind: "tablet",
		price: 399,
		colors: ["Blue", "Silver", "Pink"],
		tiers: [
			{ storage: 64, add: 0 },
			{ storage: 256, add: 180 },
		],
		summary: "All-screen iPad with A14 Bionic and USB-C.",
		highlights: [
			"10.9-inch Liquid Retina",
			"A14 Bionic",
			"Landscape front camera",
			"USB-C",
		],
	},
	{
		name: "iPad Air 11 (M2)",
		brand: "Apple",
		category: "tablets",
		kind: "tablet",
		price: 699,
		colors: ["Space Gray", "Blue", "Purple"],
		tiers: tabletStorage(130),
		summary: "M2 performance with Apple Pencil Pro support.",
		highlights: [
			"11-inch Liquid Retina",
			"Apple M2 chip",
			"Apple Pencil Pro support",
			"Touch ID",
		],
	},
	{
		name: "iPad Air 13 (M2)",
		brand: "Apple",
		category: "tablets",
		kind: "tablet",
		price: 949,
		colors: ["Space Gray", "Starlight"],
		tiers: tabletStorage(130),
		summary: "The largest iPad Air with a 13-inch display.",
		highlights: [
			"13-inch Liquid Retina",
			"Apple M2 chip",
			"Landscape stereo speakers",
			"Wi-Fi 6E",
		],
	},
	{
		name: "iPad Pro 11 (M4)",
		brand: "Apple",
		category: "tablets",
		kind: "tablet",
		price: 1199,
		colors: ["Space Gray", "Silver"],
		tiers: [
			{ storage: 256, add: 0 },
			{ storage: 512, add: 250 },
			{ storage: 1024, add: 700 },
		],
		summary: "Ultra-thin iPad Pro with Ultra Retina XDR OLED.",
		highlights: [
			"Tandem OLED display",
			"Apple M4 chip",
			"5.3 mm thin",
			"Thunderbolt / USB 4",
		],
	},
	{
		name: "iPad Pro 13 (M4)",
		brand: "Apple",
		category: "tablets",
		kind: "tablet",
		price: 1549,
		colors: ["Space Gray", "Silver"],
		tiers: [
			{ storage: 256, add: 0 },
			{ storage: 512, add: 250 },
			{ storage: 1024, add: 700 },
		],
		summary: "The ultimate iPad for creative professionals.",
		highlights: [
			"13-inch Ultra Retina XDR",
			"Apple M4 chip",
			"Nano-texture glass option",
			"Four studio-quality mics",
		],
	},
	{
		name: "iPad mini",
		brand: "Apple",
		category: "tablets",
		kind: "tablet",
		price: 599,
		colors: ["Space Gray", "Purple", "Blue"],
		tiers: tabletStorage(130),
		summary: "Small iPad with A17 Pro and Apple Intelligence.",
		highlights: [
			"8.3-inch Liquid Retina",
			"A17 Pro chip",
			"Apple Pencil Pro support",
			"Fits in one hand",
		],
	},
	{
		name: "Galaxy Tab S9 FE",
		brand: "Samsung",
		category: "tablets",
		kind: "tablet",
		price: 449,
		colors: ["Graphite", "Silver"],
		tiers: [
			{ storage: 128, add: 0 },
			{ storage: 256, add: 70 },
		],
		summary: "Water-resistant tablet with S Pen included.",
		highlights: [
			"10.9-inch 90 Hz display",
			"S Pen included",
			"IP68",
			"8,000 mAh battery",
		],
	},
	{
		name: "Galaxy Tab S9",
		brand: "Samsung",
		category: "tablets",
		kind: "tablet",
		price: 899,
		colors: ["Graphite", "Sand"],
		tiers: [
			{ storage: 128, add: 0 },
			{ storage: 256, add: 120 },
		],
		summary: "Premium AMOLED tablet with Snapdragon 8 Gen 2.",
		highlights: [
			"11-inch Dynamic AMOLED 2X",
			"Snapdragon 8 Gen 2",
			"IP68",
			"Quad AKG speakers",
		],
	},
	{
		name: "Galaxy Tab S10+",
		brand: "Samsung",
		category: "tablets",
		kind: "tablet",
		price: 1099,
		colors: ["Graphite", "Silver"],
		tiers: [
			{ storage: 256, add: 0 },
			{ storage: 512, add: 120 },
		],
		summary: "12.4-inch AMOLED tablet built for Galaxy AI.",
		highlights: [
			"12.4-inch Dynamic AMOLED 2X",
			"Galaxy AI",
			"Anti-reflective display",
			"S Pen included",
		],
	},
	{
		name: "Galaxy Tab A9+",
		brand: "Samsung",
		category: "tablets",
		kind: "tablet",
		price: 229,
		colors: ["Graphite", "Silver"],
		tiers: [
			{ storage: 64, add: 0 },
			{ storage: 128, add: 40 },
		],
		summary: "Family tablet for streaming and homework.",
		highlights: [
			"11-inch 90 Hz display",
			"Quad speakers",
			"Kids mode",
			"microSD slot",
		],
	},
	{
		name: "Tab P12",
		brand: "Lenovo",
		category: "tablets",
		kind: "tablet",
		price: 369,
		colors: ["Graphite"],
		tiers: [{ storage: 128, add: 0 }],
		summary: "12.7-inch 3K tablet with pen included.",
		highlights: [
			"12.7-inch 3K display",
			"Lenovo Tab Pen Plus",
			"JBL quad speakers",
			"10,200 mAh battery",
		],
	},
	{
		name: "Tab M11",
		brand: "Lenovo",
		category: "tablets",
		kind: "tablet",
		price: 199,
		colors: ["Graphite"],
		tiers: [
			{ storage: 64, add: 0 },
			{ storage: 128, add: 40 },
		],
		summary: "Affordable 11-inch tablet for everyday use.",
		highlights: [
			"11-inch 90 Hz",
			"Dolby Atmos speakers",
			"Reading mode",
			"microSD slot",
		],
	},
	{
		name: "Pad 6",
		brand: "Xiaomi",
		category: "tablets",
		kind: "tablet",
		price: 399,
		colors: ["Graphite", "Blue"],
		tiers: [
			{ storage: 128, add: 0 },
			{ storage: 256, add: 50 },
		],
		summary: "144 Hz 2.8K tablet with Snapdragon 870.",
		highlights: [
			"11-inch 2.8K 144 Hz",
			"Snapdragon 870",
			"Quad speakers",
			"33 W charging",
		],
	},
	{
		name: "Pad",
		brand: "OnePlus",
		category: "tablets",
		kind: "tablet",
		price: 499,
		colors: ["Green"],
		tiers: [
			{ storage: 128, add: 0 },
			{ storage: 256, add: 50 },
		],
		summary: "7:5 display ratio tablet with fast charging.",
		highlights: [
			"11.61-inch 144 Hz",
			"67 W SUPERVOOC",
			"Dolby Vision",
			"Omnibearing sound field",
		],
	},
	{
		name: "Surface Pro 11",
		brand: "Microsoft",
		category: "tablets",
		kind: "tablet",
		price: 1199,
		colors: ["Silver", "Graphite"],
		tiers: [
			{ ram: 16, storage: 256, add: 0 },
			{ ram: 16, storage: 512, add: 230 },
		],
		summary: "2-in-1 tablet that replaces a laptop.",
		highlights: [
			"13-inch PixelSense Flow",
			"Snapdragon X Plus",
			"Keyboard sold separately",
			"Copilot+ PC",
		],
	},
	{
		name: "Fire HD 10",
		brand: "Amazon",
		category: "tablets",
		kind: "tablet",
		price: 149,
		colors: ["Black", "Blue"],
		tiers: [
			{ storage: 32, add: 0 },
			{ storage: 64, add: 40 },
		],
		summary: "Budget 10-inch tablet with Alexa built in.",
		highlights: [
			"10.1-inch Full HD",
			"Up to 13 hours battery",
			"Alexa hands-free",
			"Expandable storage",
		],
	},

	// Audio
	{
		name: "AirPods 4 (ANC)",
		brand: "Apple",
		category: "audio",
		kind: "earbuds",
		price: 199,
		colors: ["White"],
		summary: "Open-fit earbuds with Active Noise Cancellation.",
		highlights: [
			"Active Noise Cancellation",
			"Personalised Spatial Audio",
			"USB-C case",
			"Up to 30 hours with case",
		],
	},
	{
		name: "AirPods Pro 2",
		brand: "Apple",
		category: "audio",
		kind: "earbuds",
		price: 279,
		colors: ["White"],
		summary: "Pro-level noise cancellation and adaptive audio.",
		highlights: [
			"Adaptive Audio",
			"Conversation Awareness",
			"Hearing Protection",
			"MagSafe case with speaker",
		],
	},
	{
		name: "AirPods Max",
		brand: "Apple",
		category: "audio",
		kind: "headphones",
		price: 579,
		colors: ["Midnight", "Starlight", "Blue", "Purple"],
		summary: "Over-ear headphones with computational audio.",
		highlights: [
			"High-fidelity audio",
			"Active Noise Cancellation",
			"Knit-mesh canopy",
			"USB-C",
		],
	},
	{
		name: "WH-1000XM5",
		brand: "Sony",
		category: "audio",
		kind: "headphones",
		price: 399,
		colors: ["Black", "Silver", "Blue"],
		summary: "Industry-leading noise cancelling over-ear headphones.",
		highlights: [
			"Eight microphones for ANC",
			"30 hours battery",
			"Speak-to-Chat",
			"Multipoint connection",
		],
	},
	{
		name: "WF-1000XM5",
		brand: "Sony",
		category: "audio",
		kind: "earbuds",
		price: 299,
		colors: ["Black", "Silver"],
		summary: "Smallest Sony flagship earbuds with premium ANC.",
		highlights: [
			"Integrated Processor V2",
			"Dynamic Driver X",
			"IPX4",
			"Wireless charging",
		],
	},
	{
		name: "QuietComfort Ultra Headphones",
		brand: "Bose",
		category: "audio",
		kind: "headphones",
		price: 449,
		colors: ["Black", "White", "Sand"],
		summary: "World-class noise cancellation with Immersive Audio.",
		highlights: [
			"CustomTune technology",
			"Bose Immersive Audio",
			"24 hours battery",
			"Premium materials",
		],
	},
	{
		name: "QuietComfort Ultra Earbuds",
		brand: "Bose",
		category: "audio",
		kind: "earbuds",
		price: 299,
		colors: ["Black", "White"],
		summary: "Noise-cancelling earbuds with Immersive Audio.",
		highlights: [
			"Aware Mode with ActiveSense",
			"Immersive Audio",
			"IPX4",
			"Up to 6 hours listening",
		],
	},
	{
		name: "Momentum 4 Wireless",
		brand: "Sennheiser",
		category: "audio",
		kind: "headphones",
		price: 349,
		colors: ["Black", "White"],
		summary: "Audiophile sound with 60 hours of battery.",
		highlights: [
			"42 mm transducers",
			"60 hours battery",
			"Adaptive ANC",
			"Sound Personalisation",
		],
	},
	{
		name: "Momentum True Wireless 4",
		brand: "Sennheiser",
		category: "audio",
		kind: "earbuds",
		price: 299,
		colors: ["Black", "Silver"],
		summary: "Hi-res earbuds with Auracast support.",
		highlights: [
			"aptX Lossless",
			"Auracast ready",
			"Adaptive ANC",
			"30 hours with case",
		],
	},
	{
		name: "Elite 10",
		brand: "Jabra",
		category: "audio",
		kind: "earbuds",
		price: 249,
		colors: ["Black", "Sand"],
		summary: "Comfortable earbuds with Dolby Atmos.",
		highlights: [
			"Dolby Head Tracking",
			"Semi-open design",
			"Six microphones for calls",
			"Multipoint",
		],
	},
	{
		name: "Galaxy Buds3 Pro",
		brand: "Samsung",
		category: "audio",
		kind: "earbuds",
		price: 249,
		colors: ["Silver", "White"],
		summary: "Blade design earbuds with Galaxy AI interpreter.",
		highlights: ["Adaptive ANC", "24-bit Hi-Fi audio", "Blade Lights", "IP57"],
	},
	{
		name: "Pixel Buds Pro 2",
		brand: "Google",
		category: "audio",
		kind: "earbuds",
		price: 249,
		colors: ["Black", "Pink", "Green"],
		summary: "Small, comfortable earbuds with Tensor A1 chip.",
		highlights: [
			"Tensor A1 chip",
			"Silent Seal 2.0",
			"Gemini hands-free",
			"IP54",
		],
	},
	{
		name: "Studio Pro",
		brand: "Beats",
		category: "audio",
		kind: "headphones",
		price: 399,
		colors: ["Black", "Sand", "Blue"],
		summary: "Wireless over-ear headphones with lossless USB-C audio.",
		highlights: [
			"Lossless audio via USB-C",
			"Personalised Spatial Audio",
			"40 hours battery",
			"Class 1 Bluetooth",
		],
	},
	{
		name: "Fit Pro",
		brand: "Beats",
		category: "audio",
		kind: "earbuds",
		price: 229,
		colors: ["Black", "White", "Purple"],
		summary: "Sport earbuds with secure-fit wingtips.",
		highlights: [
			"Flexible wingtips",
			"Active Noise Cancelling",
			"Sweat and water resistant",
			"Apple H1 chip",
		],
	},
	{
		name: "Tune 770NC",
		brand: "JBL",
		category: "audio",
		kind: "headphones",
		price: 129,
		colors: ["Black", "Blue", "White"],
		summary: "Affordable adaptive noise cancelling headphones.",
		highlights: [
			"JBL Pure Bass Sound",
			"Adaptive ANC",
			"70 hours battery",
			"Foldable design",
		],
	},
	{
		name: "Charge 5",
		brand: "JBL",
		category: "audio",
		kind: "speaker",
		price: 179,
		colors: ["Black", "Blue", "Red"],
		summary: "Portable waterproof speaker with power bank.",
		highlights: [
			"IP67 waterproof",
			"20 hours playtime",
			"Built-in power bank",
			"PartyBoost",
		],
	},
	{
		name: "Flip 6",
		brand: "JBL",
		category: "audio",
		kind: "speaker",
		price: 129,
		colors: ["Black", "Blue", "Red"],
		summary: "Compact speaker with bold JBL Original Pro Sound.",
		highlights: [
			"Two-way speaker system",
			"IP67",
			"12 hours playtime",
			"PartyBoost",
		],
	},
	{
		name: "Era 100",
		brand: "Sonos",
		category: "audio",
		kind: "speaker",
		price: 279,
		colors: ["Black", "White"],
		summary: "Smart speaker with stereo sound and voice control.",
		highlights: [
			"Stereo sound",
			"Trueplay tuning",
			"Bluetooth and Wi-Fi",
			"USB-C line-in",
		],
	},
	{
		name: "Emberton III",
		brand: "Marshall",
		category: "audio",
		kind: "speaker",
		price: 169,
		colors: ["Black", "Sand"],
		summary: "Rugged portable speaker with signature Marshall sound.",
		highlights: [
			"True Stereophonic 360°",
			"32+ hours playtime",
			"IP67",
			"Auracast",
		],
	},
	{
		name: "Ear",
		brand: "Nothing",
		category: "audio",
		kind: "earbuds",
		price: 149,
		colors: ["Black", "White"],
		summary: "Transparent earbuds with ChatGPT integration.",
		highlights: [
			"Hi-Res Audio",
			"Smart ANC",
			"Personal Sound Profile",
			"40.5 hours with case",
		],
	},

	// Wearables
	{
		name: "Apple Watch Series 10",
		brand: "Apple",
		category: "wearables",
		kind: "watch",
		price: 449,
		colors: ["Midnight", "Silver", "Pink"],
		tiers: watchSizes(1.7, 1.9, 30),
		summary: "Thinnest Apple Watch with the biggest display yet.",
		highlights: [
			"Wide-angle OLED display",
			"Sleep apnoea notifications",
			"Depth and water temperature sensor",
			"Fast charging",
		],
	},
	{
		name: "Apple Watch Ultra 2",
		brand: "Apple",
		category: "wearables",
		kind: "watch",
		price: 899,
		colors: ["Titanium", "Black"],
		tiers: [{ screen: 1.9, add: 0 }],
		summary: "Rugged titanium watch for endurance and adventure.",
		highlights: [
			"49 mm titanium case",
			"Up to 36 hours battery",
			"Precision dual-frequency GPS",
			"100 m water resistance",
		],
	},
	{
		name: "Apple Watch SE",
		brand: "Apple",
		category: "wearables",
		kind: "watch",
		price: 279,
		colors: ["Midnight", "Starlight", "Silver"],
		tiers: watchSizes(1.6, 1.8, 30),
		summary: "Essential Apple Watch features at a great price.",
		highlights: [
			"Crash Detection",
			"Heart rate notifications",
			"Swimproof",
			"Family Setup",
		],
	},
	{
		name: "Galaxy Watch7",
		brand: "Samsung",
		category: "wearables",
		kind: "watch",
		price: 319,
		colors: ["Green", "Silver", "Black"],
		tiers: watchSizes(1.3, 1.5, 30),
		summary: "Health-focused smartwatch with Galaxy AI insights.",
		highlights: [
			"BioActive sensor",
			"Energy Score",
			"Dual-frequency GPS",
			"Sapphire crystal glass",
		],
	},
	{
		name: "Galaxy Watch Ultra",
		brand: "Samsung",
		category: "wearables",
		kind: "watch",
		price: 699,
		colors: ["Titanium", "White"],
		tiers: [{ screen: 1.5, add: 0 }],
		summary: "Titanium outdoor smartwatch with 100-hour battery.",
		highlights: [
			"Grade 4 titanium",
			"10 ATM water resistance",
			"Quick button",
			"Up to 100 hours battery",
		],
	},
	{
		name: "Pixel Watch 3",
		brand: "Google",
		category: "wearables",
		kind: "watch",
		price: 399,
		colors: ["Black", "Silver", "Pink"],
		tiers: watchSizes(1.3, 1.6, 50),
		summary: "Fitbit health tracking in a domed Google design.",
		highlights: [
			"Actua display",
			"Readiness score",
			"Loss of Pulse Detection",
			"Wear OS 5",
		],
	},
	{
		name: "Forerunner 265",
		brand: "Garmin",
		category: "wearables",
		kind: "watch",
		price: 449,
		colors: ["Black", "White"],
		tiers: watchSizes(1.1, 1.3, 0),
		summary: "Running watch with AMOLED display and training readiness.",
		highlights: [
			"AMOLED touchscreen",
			"Training Readiness",
			"Multi-band GPS",
			"Up to 13 days battery",
		],
	},
	{
		name: "fēnix 8",
		brand: "Garmin",
		category: "wearables",
		kind: "watch",
		price: 999,
		colors: ["Titanium", "Black"],
		tiers: watchSizes(1.3, 1.4, 100),
		summary: "Premium multisport GPS watch with built-in flashlight.",
		highlights: [
			"AMOLED display",
			"Built-in LED flashlight",
			"Dive-rated to 40 m",
			"Voice commands",
		],
	},
	{
		name: "Venu 3",
		brand: "Garmin",
		category: "wearables",
		kind: "watch",
		price: 449,
		colors: ["Black", "Silver"],
		tiers: watchSizes(1.2, 1.4, 0),
		summary: "Lifestyle smartwatch with advanced sleep coaching.",
		highlights: [
			"Sleep coach",
			"Nap detection",
			"Wheelchair mode",
			"Up to 14 days battery",
		],
	},
	{
		name: "Charge 6",
		brand: "Fitbit",
		category: "wearables",
		kind: "watch",
		price: 159,
		colors: ["Black", "Sand"],
		tiers: [{ screen: 1.0, add: 0 }],
		summary: "Fitness tracker with built-in GPS and Google apps.",
		highlights: [
			"Built-in GPS",
			"YouTube Music controls",
			"Heart rate on gym equipment",
			"7-day battery",
		],
	},
	{
		name: "Versa 4",
		brand: "Fitbit",
		category: "wearables",
		kind: "watch",
		price: 199,
		colors: ["Black", "Pink"],
		tiers: [{ screen: 1.6, add: 0 }],
		summary: "Fitness smartwatch with 40+ exercise modes.",
		highlights: [
			"40+ exercise modes",
			"Daily Readiness Score",
			"6+ day battery",
			"Water resistant to 50 m",
		],
	},
	{
		name: "Watch GT 5",
		brand: "Huawei",
		category: "wearables",
		kind: "watch",
		price: 249,
		colors: ["Black", "Silver"],
		tiers: watchSizes(1.3, 1.4, 30),
		summary: "Stylish smartwatch with up to two weeks of battery.",
		highlights: [
			"Up to 14 days battery",
			"TruSense health system",
			"Sunflower positioning",
			"Stainless steel case",
		],
	},
	{
		name: "GTR 4",
		brand: "Amazfit",
		category: "wearables",
		kind: "watch",
		price: 199,
		colors: ["Black", "Silver"],
		tiers: [{ screen: 1.4, add: 0 }],
		summary: "Classic-looking smartwatch with dual-band GPS.",
		highlights: [
			"Dual-band GPS",
			"150+ sports modes",
			"14-day battery",
			"Alexa built-in",
		],
	},
	{
		name: "ScanWatch 2",
		brand: "Withings",
		category: "wearables",
		kind: "watch",
		price: 349,
		colors: ["Black", "White"],
		tiers: watchSizes(1.0, 1.1, 0),
		summary: "Hybrid smartwatch with medical-grade ECG.",
		highlights: [
			"Medical-grade ECG",
			"Temperature tracking",
			"30-day battery",
			"Analogue hands",
		],
	},
	{
		name: "Smart Band 9",
		brand: "Xiaomi",
		category: "wearables",
		kind: "watch",
		price: 39,
		colors: ["Black", "Silver", "Pink"],
		tiers: [{ screen: 1.6, add: 0 }],
		summary: "Affordable fitness band with a bright AMOLED screen.",
		highlights: [
			"1.62-inch AMOLED",
			"21-day battery",
			"150+ workout modes",
			"5 ATM",
		],
	},
	{
		name: "Watch Fit 3",
		brand: "Huawei",
		category: "wearables",
		kind: "watch",
		price: 159,
		colors: ["Black", "White", "Green"],
		tiers: [{ screen: 1.8, add: 0 }],
		summary: "Rectangular fitness watch with a large AMOLED display.",
		highlights: [
			"1.82-inch AMOLED",
			"Up to 10 days battery",
			"Calorie tracking",
			"Aluminium case",
		],
	},

	// Monitors
	{
		name: "UltraGear 27GR95QE",
		brand: "LG",
		category: "monitors",
		kind: "monitor",
		price: 899,
		colors: ["Black"],
		tiers: [{ screen: 27, add: 0 }],
		summary: "240 Hz OLED gaming monitor with 0.03 ms response.",
		highlights: [
			"27-inch QHD OLED",
			"240 Hz refresh rate",
			"0.03 ms GtG",
			"NVIDIA G-SYNC compatible",
		],
	},
	{
		name: "UltraFine 27UP850",
		brand: "LG",
		category: "monitors",
		kind: "monitor",
		price: 449,
		colors: ["White"],
		tiers: [{ screen: 27, add: 0 }],
		summary: "4K IPS monitor with USB-C and HDR400.",
		highlights: [
			"27-inch 4K IPS",
			"USB-C with 96 W PD",
			"DCI-P3 95%",
			"VESA DisplayHDR 400",
		],
	},
	{
		name: "UltraSharp U2724D",
		brand: "Dell",
		category: "monitors",
		kind: "monitor",
		price: 399,
		colors: ["Black"],
		tiers: [
			{ screen: 24, add: -110 },
			{ screen: 27, add: 0 },
		],
		summary: "Colour-accurate QHD monitor with 120 Hz ComfortView Plus.",
		highlights: [
			"QHD IPS Black",
			"120 Hz refresh rate",
			"ComfortView Plus",
			"USB hub",
		],
	},
	{
		name: "UltraSharp U3224KB",
		brand: "Dell",
		category: "monitors",
		kind: "monitor",
		price: 2499,
		colors: ["Silver"],
		tiers: [{ screen: 32, add: 0 }],
		summary: "6K monitor with built-in 4K webcam and Thunderbolt 4.",
		highlights: [
			"31.5-inch 6K IPS Black",
			"Thunderbolt 4 hub",
			"4K webcam",
			"Dual 14 W speakers",
		],
	},
	{
		name: "S2722QC",
		brand: "Dell",
		category: "monitors",
		kind: "monitor",
		price: 299,
		colors: ["Silver"],
		tiers: [{ screen: 27, add: 0 }],
		summary: "Affordable 4K USB-C monitor with speakers.",
		highlights: [
			"27-inch 4K",
			"USB-C 65 W",
			"Dual 3 W speakers",
			"AMD FreeSync",
		],
	},
	{
		name: "Odyssey G7",
		brand: "Samsung",
		category: "monitors",
		kind: "monitor",
		price: 549,
		colors: ["Black"],
		tiers: [
			{ screen: 27, add: 0 },
			{ screen: 32, add: 100 },
		],
		summary: "Curved 240 Hz QLED gaming monitor.",
		highlights: ["1000R curve", "240 Hz", "1 ms response", "QLED colour"],
	},
	{
		name: "Odyssey OLED G8",
		brand: "Samsung",
		category: "monitors",
		kind: "monitor",
		price: 1299,
		colors: ["Silver"],
		tiers: [{ screen: 32, add: 0 }],
		summary: "4K 240 Hz QD-OLED with glare-free finish.",
		highlights: [
			"32-inch 4K QD-OLED",
			"240 Hz",
			"OLED Glare Free",
			"Smart TV apps",
		],
	},
	{
		name: "ViewFinity S8",
		brand: "Samsung",
		category: "monitors",
		kind: "monitor",
		price: 499,
		colors: ["Black"],
		tiers: [
			{ screen: 27, add: 0 },
			{ screen: 32, add: 120 },
		],
		summary: "4K monitor for creators with HDR10.",
		highlights: [
			"4K UHD",
			"98% DCI-P3",
			"USB-C 90 W",
			"Height-adjustable stand",
		],
	},
	{
		name: "ProArt PA278CV",
		brand: "ASUS",
		category: "monitors",
		kind: "monitor",
		price: 349,
		colors: ["Black"],
		tiers: [{ screen: 27, add: 0 }],
		summary: "Calman-verified QHD monitor for colour work.",
		highlights: ["100% sRGB", "Calman Verified", "USB-C 65 W", "ProArt Preset"],
	},
	{
		name: "ROG Swift PG27AQDM",
		brand: "ASUS",
		category: "monitors",
		kind: "monitor",
		price: 999,
		colors: ["Black"],
		tiers: [{ screen: 27, add: 0 }],
		summary: "240 Hz OLED esports monitor with custom heatsink.",
		highlights: [
			"27-inch QHD OLED",
			"240 Hz",
			"Custom heatsink",
			"Anti-glare micro-texture",
		],
	},
	{
		name: "PD2706U",
		brand: "BenQ",
		category: "monitors",
		kind: "monitor",
		price: 599,
		colors: ["Silver"],
		tiers: [{ screen: 27, add: 0 }],
		summary: "4K designer monitor with Hotkey Puck.",
		highlights: [
			"27-inch 4K IPS",
			"Hotkey Puck G3",
			"USB-C 90 W",
			"M-Book mode",
		],
	},
	{
		name: "ZOWIE XL2546K",
		brand: "BenQ",
		category: "monitors",
		kind: "monitor",
		price: 499,
		colors: ["Black"],
		tiers: [{ screen: 24, add: 0 }],
		summary: "240 Hz esports monitor with DyAc+.",
		highlights: [
			"24.5-inch 240 Hz",
			"DyAc+ technology",
			"S Switch",
			"Shielding hood",
		],
	},
	{
		name: "Studio Display",
		brand: "Apple",
		category: "monitors",
		kind: "monitor",
		price: 1749,
		colors: ["Silver"],
		tiers: [{ screen: 27, add: 0 }],
		summary: "5K Retina display with 12 MP Center Stage camera.",
		highlights: [
			"27-inch 5K Retina",
			"12 MP Ultra Wide camera",
			"Six-speaker system",
			"Thunderbolt 3",
		],
	},
	{
		name: "Q27G3XMN",
		brand: "AOC",
		category: "monitors",
		kind: "monitor",
		price: 299,
		colors: ["Black"],
		tiers: [{ screen: 27, add: 0 }],
		summary: "Mini-LED gaming monitor with HDR1000.",
		highlights: [
			"336 local dimming zones",
			"VESA DisplayHDR 1000",
			"180 Hz",
			"QHD",
		],
	},
	{
		name: "M27Q",
		brand: "Gigabyte",
		category: "monitors",
		kind: "monitor",
		price: 279,
		colors: ["Black"],
		tiers: [{ screen: 27, add: 0 }],
		summary: "170 Hz QHD monitor with KVM switch.",
		highlights: ["QHD 170 Hz", "Built-in KVM", "USB-C", "92% DCI-P3"],
	},
	{
		name: "Evnia 34M2C8600",
		brand: "Philips",
		category: "monitors",
		kind: "monitor",
		price: 899,
		colors: ["Black"],
		tiers: [{ screen: 34, add: 0 }],
		summary: "Ultra-wide QD-OLED with Ambiglow.",
		highlights: ["34-inch WQHD QD-OLED", "175 Hz", "Ambiglow", "1800R curve"],
	},

	// Accessories
	{
		name: "MX Master 3S",
		brand: "Logitech",
		category: "accessories",
		kind: "mouse",
		price: 109,
		colors: ["Graphite", "White"],
		summary: "Quiet-click performance mouse with 8K DPI sensor.",
		highlights: [
			"8,000 DPI sensor",
			"Quiet Clicks",
			"MagSpeed scroll wheel",
			"USB-C charging",
		],
	},
	{
		name: "MX Keys S",
		brand: "Logitech",
		category: "accessories",
		kind: "keyboard",
		price: 119,
		colors: ["Graphite", "White"],
		summary: "Low-profile wireless keyboard with smart backlighting.",
		highlights: [
			"Smart backlighting",
			"Up to 3 devices",
			"Smart Actions",
			"USB-C",
		],
	},
	{
		name: "MX Mechanical Mini",
		brand: "Logitech",
		category: "accessories",
		kind: "keyboard",
		price: 149,
		colors: ["Graphite"],
		summary: "Compact mechanical keyboard with quiet tactile switches.",
		highlights: [
			"Low-profile mechanical switches",
			"Smart backlighting",
			"Up to 15 days with backlight",
			"Bluetooth and Logi Bolt",
		],
	},
	{
		name: "Lift Vertical Mouse",
		brand: "Logitech",
		category: "accessories",
		kind: "mouse",
		price: 79,
		colors: ["Graphite", "Pink", "White"],
		summary: "Ergonomic vertical mouse for small to medium hands.",
		highlights: [
			"57° vertical angle",
			"Quiet clicks",
			"Up to 24 months battery",
			"Logi Options+",
		],
	},
	{
		name: "Magic Keyboard with Touch ID",
		brand: "Apple",
		category: "accessories",
		kind: "keyboard",
		price: 169,
		colors: ["White", "Black"],
		summary: "Wireless keyboard with Touch ID for Macs with Apple silicon.",
		highlights: [
			"Touch ID",
			"Rechargeable battery",
			"USB-C",
			"Scissor mechanism",
		],
	},
	{
		name: "Magic Mouse",
		brand: "Apple",
		category: "accessories",
		kind: "mouse",
		price: 89,
		colors: ["White", "Black"],
		summary: "Multi-Touch surface for gestures on the Mac.",
		highlights: [
			"Multi-Touch surface",
			"USB-C charging",
			"Optimised foot design",
			"Automatic pairing",
		],
	},
	{
		name: "737 Power Bank (24,000 mAh)",
		brand: "Anker",
		category: "accessories",
		kind: "charger",
		price: 139,
		colors: ["Black"],
		summary: "140 W power bank that charges a laptop at full speed.",
		highlights: [
			"24,000 mAh",
			"140 W output",
			"Smart digital display",
			"Two USB-C and one USB-A",
		],
	},
	{
		name: "Nano Charger 65W",
		brand: "Anker",
		category: "accessories",
		kind: "charger",
		price: 49,
		colors: ["White", "Black"],
		summary: "Compact GaN charger for laptops and phones.",
		highlights: [
			"65 W USB-C",
			"GaN II technology",
			"Foldable plug",
			"ActiveShield temperature monitoring",
		],
	},
	{
		name: "35W Dual USB-C Port Power Adapter",
		brand: "Apple",
		category: "accessories",
		kind: "charger",
		price: 65,
		colors: ["White"],
		summary: "Charge two devices at once with one compact adapter.",
		highlights: [
			"Two USB-C ports",
			"35 W total output",
			"Compact design",
			"Works with iPhone and MacBook Air",
		],
	},
	{
		name: "BoostCharge Pro 3-in-1",
		brand: "Belkin",
		category: "accessories",
		kind: "charger",
		price: 129,
		colors: ["Black", "White"],
		summary: "MagSafe stand for iPhone, Apple Watch, and AirPods.",
		highlights: [
			"Qi2 15 W",
			"Apple Watch fast charging",
			"Adjustable phone angle",
			"Power adapter included",
		],
	},
	{
		name: "Samsung T7 Shield Portable SSD",
		brand: "Samsung",
		category: "accessories",
		kind: "ssd",
		price: 89,
		colors: ["Black", "Blue"],
		tiers: [
			{ storage: 1024, add: 0 },
			{ storage: 2048, add: 70 },
			{ storage: 4096, add: 210 },
		],
		summary: "Rugged portable SSD with up to 1,050 MB/s.",
		highlights: [
			"Up to 1,050 MB/s",
			"IP65 dust and water resistance",
			"3 m drop resistant",
			"USB 3.2 Gen 2",
		],
	},
	{
		name: "Extreme Portable SSD V2",
		brand: "SanDisk",
		category: "accessories",
		kind: "ssd",
		price: 99,
		colors: ["Black"],
		tiers: [
			{ storage: 1024, add: 0 },
			{ storage: 2048, add: 80 },
		],
		summary: "Pocket-size SSD with carabiner loop.",
		highlights: [
			"Up to 1,050 MB/s",
			"IP65",
			"Carabiner loop",
			"5-year warranty",
		],
	},
	{
		name: "555 USB-C Hub (8-in-1)",
		brand: "Anker",
		category: "accessories",
		kind: "charger",
		price: 59,
		colors: ["Graphite"],
		summary: "Adds HDMI, Ethernet, SD, and USB ports to your laptop.",
		highlights: [
			"4K HDMI",
			"100 W pass-through",
			"Gigabit Ethernet",
			"SD and microSD readers",
		],
	},
	{
		name: "TS4 Thunderbolt 4 Dock",
		brand: "CalDigit",
		category: "accessories",
		kind: "charger",
		price: 429,
		colors: ["Space Gray"],
		summary: "18-port dock for a one-cable desk setup.",
		highlights: [
			"18 ports",
			"98 W charging",
			"2.5 GbE",
			"Single 8K or dual 6K displays",
		],
	},
	{
		name: "K2 Pro",
		brand: "Keychron",
		category: "accessories",
		kind: "keyboard",
		price: 109,
		colors: ["Graphite", "White"],
		summary: "Hot-swappable 75% mechanical keyboard.",
		highlights: [
			"Hot-swappable switches",
			"QMK/VIA support",
			"Mac and Windows layouts",
			"RGB backlight",
		],
	},
	{
		name: "DeathAdder V3",
		brand: "Razer",
		category: "accessories",
		kind: "mouse",
		price: 89,
		colors: ["Black", "White"],
		summary: "Ultra-light ergonomic esports mouse.",
		highlights: [
			"59 g ultra-light",
			"Focus Pro 30K sensor",
			"8,000 Hz polling",
			"Optical switches Gen-3",
		],
	},
	{
		name: "BookArc",
		brand: "Twelve South",
		category: "accessories",
		kind: "charger",
		price: 59,
		colors: ["Silver", "Space Gray"],
		summary: "Vertical stand for MacBook in clamshell mode.",
		highlights: [
			"Space-saving vertical design",
			"Fits all MacBooks",
			"Cable management",
			"Aluminium",
		],
	},
	{
		name: "USB-C Multiport Adapter V2",
		brand: "Satechi",
		category: "accessories",
		kind: "charger",
		price: 99,
		colors: ["Space Gray", "Silver"],
		summary: "Aluminium hub with 4K HDMI and Ethernet.",
		highlights: [
			"4K 60 Hz HDMI",
			"Gigabit Ethernet",
			"USB-C PD 100 W",
			"Aluminium finish",
		],
	},
	{
		name: "Apple Pencil Pro",
		brand: "Apple",
		category: "accessories",
		kind: "charger",
		price: 149,
		colors: ["White"],
		summary: "Squeeze, barrel roll, and haptic feedback for iPad.",
		highlights: [
			"Squeeze gesture",
			"Barrel roll",
			"Haptic feedback",
			"Find My support",
		],
	},
	{
		name: "45W Power Adapter",
		brand: "Samsung",
		category: "accessories",
		kind: "charger",
		price: 49,
		colors: ["White", "Black"],
		summary: "Super Fast Charging 2.0 for Galaxy devices.",
		highlights: [
			"45 W Super Fast Charging 2.0",
			"USB-C to C cable included",
			"Compact design",
			"PPS support",
		],
	},

	// Gaming
	{
		name: "PlayStation 5 Slim",
		brand: "Sony",
		category: "gaming",
		kind: "controller",
		price: 499,
		colors: ["White"],
		tiers: [{ storage: 1024, add: 0 }],
		summary: "Slimmer PS5 with 1 TB SSD and disc drive.",
		highlights: [
			"1 TB SSD",
			"Ultra HD Blu-ray",
			"DualSense controller included",
			"Ray tracing",
		],
	},
	{
		name: "PlayStation 5 Pro",
		brand: "Sony",
		category: "gaming",
		kind: "controller",
		price: 799,
		colors: ["White"],
		tiers: [{ storage: 2048, add: 0 }],
		summary: "The most powerful PlayStation with PSSR upscaling.",
		highlights: [
			"2 TB SSD",
			"PlayStation Spectral Super Resolution",
			"Wi-Fi 7",
			"Advanced ray tracing",
		],
	},
	{
		name: "DualSense Wireless Controller",
		brand: "Sony",
		category: "gaming",
		kind: "controller",
		price: 74,
		colors: ["White", "Black", "Blue", "Red"],
		summary: "Haptic feedback and adaptive triggers for PS5.",
		highlights: [
			"Haptic feedback",
			"Adaptive triggers",
			"Built-in microphone",
			"USB-C",
		],
	},
	{
		name: "DualSense Edge",
		brand: "Sony",
		category: "gaming",
		kind: "controller",
		price: 239,
		colors: ["White"],
		summary: "Pro controller with swappable stick modules.",
		highlights: [
			"Replaceable stick modules",
			"Back buttons",
			"Custom profiles",
			"Carrying case",
		],
	},
	{
		name: "Xbox Series X",
		brand: "Microsoft",
		category: "gaming",
		kind: "controller",
		price: 549,
		colors: ["Black"],
		tiers: [
			{ storage: 1024, add: 0 },
			{ storage: 2048, add: 150 },
		],
		summary: "4K gaming at up to 120 FPS with Quick Resume.",
		highlights: [
			"12 teraflops",
			"4K at up to 120 FPS",
			"Quick Resume",
			"Game Pass ready",
		],
	},
	{
		name: "Xbox Series S",
		brand: "Microsoft",
		category: "gaming",
		kind: "controller",
		price: 299,
		colors: ["White", "Black"],
		tiers: [
			{ storage: 512, add: 0 },
			{ storage: 1024, add: 50 },
		],
		summary: "Compact all-digital console for next-gen gaming.",
		highlights: [
			"1440p at up to 120 FPS",
			"All-digital",
			"Quick Resume",
			"Smallest Xbox ever",
		],
	},
	{
		name: "Xbox Wireless Controller",
		brand: "Microsoft",
		category: "gaming",
		kind: "controller",
		price: 59,
		colors: ["Black", "White", "Blue"],
		summary: "Hybrid D-pad and textured grip for Xbox and PC.",
		highlights: ["Hybrid D-pad", "Textured grip", "Share button", "Bluetooth"],
	},
	{
		name: "Nintendo Switch – OLED Model",
		brand: "Nintendo",
		category: "gaming",
		kind: "controller",
		price: 349,
		colors: ["White", "Red"],
		tiers: [{ storage: 64, add: 0 }],
		summary: "Vivid 7-inch OLED screen for handheld and TV play.",
		highlights: [
			"7-inch OLED screen",
			"Wide adjustable stand",
			"64 GB storage",
			"Wired LAN port in dock",
		],
	},
	{
		name: "Nintendo Switch Lite",
		brand: "Nintendo",
		category: "gaming",
		kind: "controller",
		price: 219,
		colors: ["Blue", "Purple", "Sand"],
		tiers: [{ storage: 32, add: 0 }],
		summary: "Compact, lightweight Switch for handheld play.",
		highlights: [
			"Handheld only",
			"Integrated controls",
			"Lightweight",
			"Compatible with Switch games",
		],
	},
	{
		name: "Switch Pro Controller",
		brand: "Nintendo",
		category: "gaming",
		kind: "controller",
		price: 69,
		colors: ["Black"],
		summary: "Traditional controller for long Switch sessions.",
		highlights: [
			"HD rumble",
			"amiibo support",
			"Up to 40 hours battery",
			"Motion controls",
		],
	},
	{
		name: "Steam Deck OLED",
		brand: "Valve",
		category: "gaming",
		kind: "controller",
		price: 569,
		colors: ["Black"],
		tiers: [
			{ storage: 512, add: 0 },
			{ storage: 1024, add: 110 },
		],
		summary: "Handheld PC with HDR OLED screen.",
		highlights: [
			"7.4-inch HDR OLED",
			"Up to 90 Hz",
			"Wi-Fi 6E",
			"50 Wh battery",
		],
	},
	{
		name: "ROG Ally X",
		brand: "ASUS",
		category: "gaming",
		kind: "controller",
		price: 899,
		colors: ["Black"],
		tiers: [{ ram: 24, storage: 1024, add: 0 }],
		summary: "Windows handheld with 80 Wh battery.",
		highlights: [
			"AMD Ryzen Z1 Extreme",
			"24 GB LPDDR5X",
			"80 Wh battery",
			"7-inch 120 Hz",
		],
	},
	{
		name: "Meta Quest 3",
		brand: "Meta",
		category: "gaming",
		kind: "controller",
		price: 549,
		colors: ["White"],
		tiers: [{ storage: 512, add: 0 }],
		summary: "Mixed reality headset with full-colour passthrough.",
		highlights: [
			"4K+ Infinite Display",
			"Snapdragon XR2 Gen 2",
			"Full-colour passthrough",
			"Touch Plus controllers",
		],
	},
	{
		name: "Meta Quest 3S",
		brand: "Meta",
		category: "gaming",
		kind: "controller",
		price: 329,
		colors: ["White"],
		tiers: [
			{ storage: 128, add: 0 },
			{ storage: 256, add: 110 },
		],
		summary: "Affordable mixed reality headset.",
		highlights: [
			"Mixed reality",
			"Snapdragon XR2 Gen 2",
			"Action button",
			"Touch Plus controllers",
		],
	},
	{
		name: "BlackShark V2 Pro",
		brand: "Razer",
		category: "gaming",
		kind: "headphones",
		price: 199,
		colors: ["Black", "White"],
		summary: "Wireless esports headset with THX Spatial Audio.",
		highlights: [
			"HyperSpeed Wireless",
			"TriForce Titanium 50 mm drivers",
			"70 hours battery",
			"Detachable mic",
		],
	},
	{
		name: "PRO X SUPERLIGHT 2",
		brand: "Logitech",
		category: "gaming",
		kind: "mouse",
		price: 169,
		colors: ["Black", "White", "Pink"],
		summary: "60 g wireless esports mouse with HERO 2 sensor.",
		highlights: [
			"60 g",
			"HERO 2 sensor",
			"LIGHTFORCE switches",
			"95 hours battery",
		],
	},
	{
		name: "Arctis Nova 7",
		brand: "SteelSeries",
		category: "gaming",
		kind: "headphones",
		price: 199,
		colors: ["Black", "White"],
		summary: "Multi-platform wireless gaming headset.",
		highlights: [
			"Simultaneous 2.4 GHz and Bluetooth",
			"38 hours battery",
			"ClearCast Gen 2 mic",
			"360° Spatial Audio",
		],
	},
	{
		name: "Ultimate Bluetooth Controller",
		brand: "8BitDo",
		category: "gaming",
		kind: "controller",
		price: 69,
		colors: ["Black", "White"],
		summary: "Controller with charging dock and Hall effect sticks.",
		highlights: [
			"Hall effect joysticks",
			"Charging dock",
			"Switch, Windows, and Steam Deck",
			"Back paddles",
		],
	},
];
