/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories/$slug'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as AdminVariantsRouteImport } from './routes/admin/variants'
import { Route as AdminShippingRouteImport } from './routes/admin/shipping'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminOptionsRouteImport } from './routes/admin/options'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AccountReviewsRouteImport } from './routes/account/reviews'
import { Route as AccountAddressesRouteImport } from './routes/account/addresses'
import { Route as LandingWithdrawalRouteImport } from './routes/_landing/withdrawal'
import { Route as LandingTrackRouteImport } from './routes/_landing/track'
import { Route as LandingTermsRouteImport } from './routes/_landing/terms'
import { Route as LandingShippingRouteImport } from './routes/_landing/shipping'
import { Route as LandingReturnsRouteImport } from './routes/_landing/returns'
import { Route as LandingPrivacyRouteImport } from './routes/_landing/privacy'
import { Route as LandingImpressumRouteImport } from './routes/_landing/impressum'
import { Route as LandingFaqRouteImport } from './routes/_landing/faq'
import { Route as LandingContactRouteImport } from './routes/_landing/contact'
import { Route as LandingAboutRouteImport } from './routes/_landing/about'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AccountOrdersIndexRouteImport } from './routes/account/orders/index'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account/orders/$orderId'

const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVariantsRoute = AdminVariantsRouteImport.update({
  id: '/variants',
  path: '/variants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShippingRoute = AdminShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOptionsRoute = AdminOptionsRouteImport.update({
  id: '/options',
  path: '/options',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AccountReviewsRoute = AccountReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const LandingWithdrawalRoute = LandingWithdrawalRouteImport.update({
  id: '/_landing/withdrawal',
  path: '/withdrawal',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingTrackRoute = LandingTrackRouteImport.update({
  id: '/_landing/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingTermsRoute = LandingTermsRouteImport.update({
  id: '/_landing/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingShippingRoute = LandingShippingRouteImport.update({
  id: '/_landing/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingReturnsRoute = LandingReturnsRouteImport.update({
  id: '/_landing/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPrivacyRoute = LandingPrivacyRouteImport.update({
  id: '/_landing/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingImpressumRoute = LandingImpressumRouteImport.update({
  id: '/_landing/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingFaqRoute = LandingFaqRouteImport.update({
  id: '/_landing/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingContactRoute = LandingContactRouteImport.update({
  id: '/_landing/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingAboutRoute = LandingAboutRouteImport.update({
  id: '/_landing/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AccountRoute,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/about': typeof LandingAboutRoute
  '/contact': typeof LandingContactRoute
  '/faq': typeof LandingFaqRoute
  '/impressum': typeof LandingImpressumRoute
  '/privacy': typeof LandingPrivacyRoute
  '/returns': typeof LandingReturnsRoute
  '/shipping': typeof LandingShippingRoute
  '/terms': typeof LandingTermsRoute
  '/track': typeof LandingTrackRoute
  '/withdrawal': typeof LandingWithdrawalRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/options': typeof AdminOptionsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/variants': typeof AdminVariantsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/about': typeof LandingAboutRoute
  '/contact': typeof LandingContactRoute
  '/faq': typeof LandingFaqRoute
  '/impressum': typeof LandingImpressumRoute
  '/privacy': typeof LandingPrivacyRoute
  '/returns': typeof LandingReturnsRoute
  '/shipping': typeof LandingShippingRoute
  '/terms': typeof LandingTermsRoute
  '/track': typeof LandingTrackRoute
  '/withdrawal': typeof LandingWithdrawalRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/options': typeof AdminOptionsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/variants': typeof AdminVariantsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/account/orders': typeof AccountOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_landing/about': typeof LandingAboutRoute
  '/_landing/contact': typeof LandingContactRoute
  '/_landing/faq': typeof LandingFaqRoute
  '/_landing/impressum': typeof LandingImpressumRoute
  '/_landing/privacy': typeof LandingPrivacyRoute
  '/_landing/returns': typeof LandingReturnsRoute
  '/_landing/shipping': typeof LandingShippingRoute
  '/_landing/terms': typeof LandingTermsRoute
  '/_landing/track': typeof LandingTrackRoute
  '/_landing/withdrawal': typeof LandingWithdrawalRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/options': typeof AdminOptionsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/variants': typeof AdminVariantsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/about'
    | '/contact'
    | '/faq'
    | '/impressum'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/terms'
    | '/track'
    | '/withdrawal'
    | '/account/addresses'
    | '/account/reviews'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/options'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/variants'
    | '/api/contact'
    | '/api/uploadthing'
    | '/categories/$slug'
    | '/products/$slug'
    | '/account/'
    | '/admin/'
    | '/categories/'
    | '/products/'
    | '/account/orders/$orderId'
    | '/api/auth/$'
    | '/api/webhooks/stripe'
    | '/account/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/about'
    | '/contact'
    | '/faq'
    | '/impressum'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/terms'
    | '/track'
    | '/withdrawal'
    | '/account/addresses'
    | '/account/reviews'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/options'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/variants'
    | '/api/contact'
    | '/api/uploadthing'
    | '/categories/$slug'
    | '/products/$slug'
    | '/account'
    | '/admin'
    | '/categories'
    | '/products'
    | '/account/orders/$orderId'
    | '/api/auth/$'
    | '/api/webhooks/stripe'
    | '/account/orders'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_auth/verify-email'
    | '/_landing/about'
    | '/_landing/contact'
    | '/_landing/faq'
    | '/_landing/impressum'
    | '/_landing/privacy'
    | '/_landing/returns'
    | '/_landing/shipping'
    | '/_landing/terms'
    | '/_landing/track'
    | '/_landing/withdrawal'
    | '/account/addresses'
    | '/account/reviews'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/options'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/variants'
    | '/api/contact'
    | '/api/uploadthing'
    | '/categories/$slug'
    | '/products/$slug'
    | '/account/'
    | '/admin/'
    | '/categories/'
    | '/products/'
    | '/account/orders/$orderId'
    | '/api/auth/$'
    | '/api/webhooks/stripe'
    | '/account/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LandingAboutRoute: typeof LandingAboutRoute
  LandingContactRoute: typeof LandingContactRoute
  LandingFaqRoute: typeof LandingFaqRoute
  LandingImpressumRoute: typeof LandingImpressumRoute
  LandingPrivacyRoute: typeof LandingPrivacyRoute
  LandingReturnsRoute: typeof LandingReturnsRoute
  LandingShippingRoute: typeof LandingShippingRoute
  LandingTermsRoute: typeof LandingTermsRoute
  LandingTrackRoute: typeof LandingTrackRoute
  LandingWithdrawalRoute: typeof LandingWithdrawalRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/variants': {
      id: '/admin/variants'
      path: '/variants'
      fullPath: '/admin/variants'
      preLoaderRoute: typeof AdminVariantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipping': {
      id: '/admin/shipping'
      path: '/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AdminShippingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/options': {
      id: '/admin/options'
      path: '/options'
      fullPath: '/admin/options'
      preLoaderRoute: typeof AdminOptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/reviews': {
      id: '/account/reviews'
      path: '/reviews'
      fullPath: '/account/reviews'
      preLoaderRoute: typeof AccountReviewsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_landing/withdrawal': {
      id: '/_landing/withdrawal'
      path: '/withdrawal'
      fullPath: '/withdrawal'
      preLoaderRoute: typeof LandingWithdrawalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/track': {
      id: '/_landing/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof LandingTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/terms': {
      id: '/_landing/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof LandingTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/shipping': {
      id: '/_landing/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof LandingShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/returns': {
      id: '/_landing/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof LandingReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/privacy': {
      id: '/_landing/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof LandingPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/impressum': {
      id: '/_landing/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof LandingImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/faq': {
      id: '/_landing/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof LandingFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/contact': {
      id: '/_landing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof LandingContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/about': {
      id: '/_landing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LandingAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/orders'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountReviewsRoute: typeof AccountReviewsRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountReviewsRoute: AccountReviewsRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminOptionsRoute: typeof AdminOptionsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShippingRoute: typeof AdminShippingRoute
  AdminVariantsRoute: typeof AdminVariantsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminOptionsRoute: AdminOptionsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShippingRoute: AdminShippingRoute,
  AdminVariantsRoute: AdminVariantsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LandingAboutRoute: LandingAboutRoute,
  LandingContactRoute: LandingContactRoute,
  LandingFaqRoute: LandingFaqRoute,
  LandingImpressumRoute: LandingImpressumRoute,
  LandingPrivacyRoute: LandingPrivacyRoute,
  LandingReturnsRoute: LandingReturnsRoute,
  LandingShippingRoute: LandingShippingRoute,
  LandingTermsRoute: LandingTermsRoute,
  LandingTrackRoute: LandingTrackRoute,
  LandingWithdrawalRoute: LandingWithdrawalRoute,
  ApiContactRoute: ApiContactRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
